title: Rodrigo Piña Lépiz
logo: /assets/img/logo.png
description: Al participar en el estudio de procesos y 
negocios; realicé el análisis de datos de
las diferentes etapas que integran la 
modernización de una empresa y
contribuí en la identificación de sus 
fortalezas y áreas de oportunidad. En 
tanto, fui desarrollando una curva de 
adaptabilidad para enfrentar los retos 
que se me presentan, colaborando en
equipo bajo un esquema de trabajo que 
me permite aprender mientras comienzo 
a entregar resultados de forma 
progresiva.
Considero que enseñar es una buena 
forma de reafirmar el conocimiento o 
experiencia que he adquirido; por lo que 
he participado en la capacitación de 
personal.
.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
